name: build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on:
      - ubuntu-latest
      - macos-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: '>=1.20.0'

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download Go modules
        run: go mod download

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test ./...
